// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf881uTw5b9AblYZ5J8eTncnesZ_BUOzQ',
    appId: '1:909432620900:web:5109d225502f16f7ebdc71',
    messagingSenderId: '909432620900',
    projectId: 'flutter-app-7f60c',
    authDomain: 'flutter-app-7f60c.firebaseapp.com',
    storageBucket: 'flutter-app-7f60c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrn5YxcFezo2Y-Ikp7Oqk2t1oHVbeZiBE',
    appId: '1:909432620900:android:7c595bcd7c3ceb22ebdc71',
    messagingSenderId: '909432620900',
    projectId: 'flutter-app-7f60c',
    storageBucket: 'flutter-app-7f60c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQBVFQGmfIJVy91x8O2fapzJkRnqdJgXg',
    appId: '1:909432620900:ios:445a9b3dd9ff4d61ebdc71',
    messagingSenderId: '909432620900',
    projectId: 'flutter-app-7f60c',
    storageBucket: 'flutter-app-7f60c.appspot.com',
    iosClientId:
        '909432620900-2qnudem3jjbn33as5g6co9p3h870depv.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalprject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQBVFQGmfIJVy91x8O2fapzJkRnqdJgXg',
    appId: '1:909432620900:ios:445a9b3dd9ff4d61ebdc71',
    messagingSenderId: '909432620900',
    projectId: 'flutter-app-7f60c',
    storageBucket: 'flutter-app-7f60c.appspot.com',
    iosClientId:
        '909432620900-2qnudem3jjbn33as5g6co9p3h870depv.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalprject',
  );
}
